### ISSUE TITLE
Общий блок, для плагинов WT Content Like и WT Ya.share2

### ISSUE THREAD

**Issue by webarion** [sergeytolkachyov/WT-Ya.share2-Joomla-social-share-content-plugin#2]
Здравствуйте Сергей! Скажите пожалуйста, нет ли возможности, нативно сделать так, чтобы пользовательские макеты этих плагинов, были обёрнуты общим блоком?
Сейчас, мне приходится делать это с помощью JavaScript.
![screen](https://github.com/sergeytolkachyov/WT-Ya.share2-Joomla-social-share-content-plugin/assets/28953448/be8a7a25-22af-4ee7-abf0-5f923c68c590)

**Comment by sergeytolkachyov** [comment]
Это проще делается. Зайдите по FTP в папку с плагином/tmpl. Там будет файл макета вывода по умоляю default.php. Скопируйте его, переименуйте и залейте обратно. В этом файле творите всё, что душе угодно. В настройках плагина выберите ваш макет, он появится в списке. В имени макета не нужно использовать символ подчёркивания. 
![Screenshot_2023-09-03-22-01-06-325_com android chrome](https://github.com/sergeytolkachyov/WT-Ya.share2-Joomla-social-share-content-plugin/assets/6236403/3bb93a85-8121-4606-8bea-3d23ed0cf44c)

Если с joomla работаете - приходите в чат русскоязычного Joomla-сообщечтва в телеграме https://t.me/joomlaru

**Comment by webarion** [comment]
Я это сделал. У меня свои макеты для обоих плагинов. Но, они выводятся друг за другом. А я хотел бы запихнуть макеты из обоих плагинов в один общий div. Либо, я что-то не понимаю?
В телеграм подписался.

**Comment by sergeytolkachyov** [comment]
Шаблон сайта свой, самописный? Если нужно обернуть в div всю область вывода плагинами, то тогда это делается переопределением макета. Вот [эту](https://github.com/joomla/joomla-cms/blob/3bb67d55ad442e0979487809fdb7c608434c386a/components/com_content/tmpl/category/blog_item.php#L61) и подобные строки оберните в нужный div в своём шаблоне.
![image](https://github.com/sergeytolkachyov/WT-Ya.share2-Joomla-social-share-content-plugin/assets/6236403/96a159c2-05a0-405a-95ae-df8e9e0c89ca)
Переопределения складывать в `templates/<ваш_шаблон>/html/<компонент>/<вид>`. Копировать из папки с компонентом: components/<компонент>/tmpl/<вид>. Допустим из `components/com_content/tmpl/category` все файлы, начинающиеся с  `blog` копируем в папку с шаблоном `templates/<ваш_шаблон>/html/com_content/category`. И тогда в этих файлах тоже можно творить всё, что хотите.

**Comment by webarion** [comment]
Понял. Благодарю вас!
